services: docker
language: python

branches:
  only:
    - master

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc


jobs:
  include:
    - stage: build
      before_install:
        - pip install poetry
      install:
        - poetry install
      script: python generate-osrm.py
